name: Jupyter Notebook
on: [push]

jobs:
  notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter
          pip install ipykernel
          python -m ipykernel install --user --name python3 --display-name "Python 3"
          pip install -r requirements.txt
          
      - name: Execute notebook
        run: |
          jupyter nbconvert --to notebook --execute *.ipynb 